### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by CodingMadeEasy** [adamgruber/mochawesome#124]
Hello, 

I was wondering how I can use mochawesome with the mocha hot loader or if there was a way to refresh the page when the html file is generated so that I can see the results of my tests real time instead of having to refresh every single time. 

I was also wondering since the 2.0 update, if there's a way to access the React component so we can integrate it as part of our react applications so the hot reloading could be handled by react itself. 

Thanks for your time.

**Comment by adamgruber** [comment]
The report is not currently available as a separate React component that can be imported into other apps but it is an interesting idea. The entire report is built as a single page app though and having just the main report component outside the app probably wouldn't work because you would be missing styles and other functionality.
