### ISSUE TITLE
mochawesome module size 1.5.5 -> 2.0.x

### ISSUE THREAD

**Issue by tiagomestre** [adamgruber/mochawesome#133]
At this moment, in my opinion, the new versions of mochawesome (2.0.x) create too much impact in continuous integration where each build is from a clean slate.

Version size comparison: **v1.5.5** -> **v2.0.3** (not including dev dependencies)

**Size:** ~12mb -> ~116mb
**Files:** 1667 -> 95635
**Folders:** 174 -> 8418

The cause of this massive change was the inclusion of the **material-design-icons** module (mochawesome-report-generator dependency).

 **material-design-icons**:

**Size:** ~82mb
**Files:** 89 814
**Folders:** 8 002

Even though I'm still going to use version 1.5.5 to generate the html report, I think the size of the module is something to take in consideration.

**Possible solutions**:

- Revert to the old icons/resources
- Include only the necessary resources from material-design-icons directly inside the mochawesome-report-generator dependency module.

**Comment by adamgruber** [comment]
@tiagomestre Good find. The problem wasn't the addition of `material-design-icons` itself but the fact that it was listed as a dependency instead of a devDependency. I have released `mochawesome 2.0.4` which points to version `1.1.0` of `mochawesome-report-generator` which no longer contains packages that were only needed during development.  It should greatly reduce the overall package size. Please upgrade and let me know how it goes.

**Comment by tiagomestre** [comment]
Much better now, thanks!
