### ISSUE TITLE
Add the ability to customize the left menu drill down level

### ISSUE THREAD

**Issue by KevinHaisol** [adamgruber/mochawesome#152]
When expanding the navigation menu on the left, it defaults to a max of 3 levels. (IE: test -> describe block).  I have 4 blocks and would like the navigation level customization.  (IE:  Option:  menuLevels: 4).  It could default to 3.

**Comment by KevinHaisol** [comment]
Could you also make the menu levels collapsable?

**Comment by adamgruber** [comment]
There's currently no max set for menu levels. It will render as many nested describes as you have. Here's a test with 5 levels: 

<img width="182" alt="screen shot 2017-04-26 at 4 11 03 pm" src="https://cloud.githubusercontent.com/assets/2378900/25454593/00ad80d2-2a9b-11e7-8eeb-a5f489e86d87.png">

As for making them collapsible, its not something I'd look into adding right now. It would require adding state to each menu item and thus extra complexity. Plus as soon as you refresh the page, that state is lost since there's no persistence in the report. So if you're collapsing things to isolate a specific suite then any time you generate a new report you'll have to start collapsing things all over again. I'm okay with a long list for now.

**Comment by KevinHaisol** [comment]
My bad, was thrown off by the duplicate describes for multiple files.  I like it, just wanted to see if it was configurable.  I like the report, and tool, works great. thanks.

**Comment by Tsvetkovv** [comment]
@adamgruber, can I set checked triggers by default? I'm setting CI to present the report to QA and I don't want to see passed test by default.

**Comment by adamgruber** [comment]
@Tsvetkovv You cannot currently set the filters by default but that is a planned future feature.
