### ISSUE TITLE
Opening report takes a very long time

### ISSUE THREAD

**Issue by HeikoH** [adamgruber/mochawesome#162]
I have about 1300 Mocha tests and opening `mochawesome.html` takes about 35 seconds which seems a bit high...
What can I do to make it load faster (or is reducing the number of tests the only option?)

![image](https://cloud.githubusercontent.com/assets/2171931/26744510/237ad822-479b-11e7-913c-e538fdd17183.png)
This is on macOS Chrome 58.0.3029.110

**Comment by adamgruber** [comment]
There are a couple things at play here:
1. All of the report data is bootstrapped into the report as stringified JSON via a data attribute on main DOM element. The string is then scraped and parsed to get the data into the store. Having a lot of tests means a lot of data to be loaded in.
2. All suites/tests are rendered into the DOM so for your case that would be at minimum 1300 `<div>`s. In practice this number is much higher because each test contains child elements that must be rendered.

With these things in mind, I am looking into some ways to speed up the loading. Specifically I'd like to try out a library like [react-virtualized](https://github.com/bvaughn/react-virtualized) so the report would only render a fraction of the tests into the DOM at a time as needed.

That said, finding time to actually implement changes has been tough lately so I can't say how soon I may get to it.

**Comment by adamgruber** [comment]
@HeikoH It also depends on how your tests are structured and if you have a lot of nesting going on. A flat list of tests will load quicker than a deeply nested tree. Can you give me a sample of your test setup showing your basic structure of suites and tests?

**Comment by HeikoH** [comment]
On average I think I have about 2-3 nested describes.

**Comment by adamgruber** [comment]
I looked into this a bit more and while the number of DOM elements is absolutely a main part of the issue, another possible reason is how the elements are laid out. It's possible that switching to a Flexbox layout might speed things up. Again, not sure when I'd be able to test that out but it's another idea.

**Comment by adamgruber** [comment]
Found one more possible improvement. The JSON that is generated includes consolidated arrays for the tests (`allTests`, `allPending`, `allPasses` and `allFailures`). With a large number of tests, this is a lot of extra data that is not currently used to render the report. These properties can either be dropped altogether or before the data is passed into the report generator. Should cut down on the file size of the HTML considerably.

**Comment by adamgruber** [comment]
v3.0.0 was just released which addresses some performance issues. The main issue is that a large test suite results in a large number of elements being rendered to the DOM. In v3.0.0, the number of DOM elements that get rendered has been reduced which should help. Also, some enhancements were made to improve perceived performance like showing stats and loading animations so you aren't staring at a blank screen while the report loads. There are likely more improvements to be made however the nested structure of things makes this a difficult problem to solve.
