### ISSUE TITLE
how to add a relative link through addReporterContext in 2.3.0 +?

### ISSUE THREAD

**Issue by npopov-d3** [adamgruber/mochawesome#175]
Hello, i've been using this code in 2.0.0:
```
let partial = "testfiles/test1"; // <- this point to a system folder like /users/me/myproj/reports/mochawesomerun1/testfiles/test1

let mylink = '<a href=' + partial +  '>' + 'click to see inside test1 files' + '</a>';
addReporterContext(that, {
       title: "test folder (click the links to see contents)",
       value: mylink
});
```
which worked fine, however, after upgrading to 2.3.0,
mochawesome now slaps extra set of double quotes around the HTML, and the link is not rendered.

Could you suggest a workaround for this case? For now i've downgraded back to 2.0.

**Comment by adamgruber** [comment]
What was the behavior of your link? Did it open a browser window or a local folder on your desktop?

Passing HTML like that was a bit of a loophole, which was closed in 2.1.1 by removing `dangerouslySetInnerHTML` from the code snippet component. The component will no longer be able to render HTML that you pass. You can pass links as strings in your `value` prop but it expects links to use the `http` or `ftp` protocol. I don't think there is any workaround since it was kind of a bug to begin with.

**Comment by npopov-d3** [comment]
Clicking the link switched the web browser window context from the report to whatever it points to, in my case, a browsable system directory with test files. My problem with passing reporter strings that look like URLs is that at the time of creating report i do not know the full url, because the reports can be hosted by different http servers depending on where the tests are run. Why not introduce a method to pass a custom html snippet into the reporter? This would be cleaner than doing some magic that converts a string into an image, url or text...

**Comment by adamgruber** [comment]
The `addContext` method is meant to be simple and limited. If I add in the ability to pass whatever as an argument then it gets very complex and I have to do even more magic to ensure that whatever gets passed in will not break the report somehow.

**Comment by mingfang** [comment]
Being able to add relative links is critical for test reports.
Please reopen this issue.

**Comment by wan54** [comment]
I have this need and came up with these https://gist.github.com/wan54/7dd042bb8aadfecc98a7a7327a24a13d
