### ISSUE TITLE
Show mochaawesome html report in jenkins 

### ISSUE THREAD

**Issue by RamiaSaidawi** [adamgruber/mochawesome#180]
Hi, 
Thank you for the great work you are doing, i am using mochaawesome report in my api testing,  i dont know how i can make jenkins show the report as part of the results page. 
I used the html report option in jenkins and gave it path to where the mochaawesome html report is, but i was not able to lunch it correctly,  do you know how i can achieve this 
Many thanks for your help 
Ramia

**Comment by adamgruber** [comment]
I've never set up a Jenkins job to display the report. I'm sure it's possible but figuring out how is a bit out of scope here. There's nothing about the reporter itself that would prevent this.

**Comment by marcowork** [comment]
Hi @RamiaSaidawi 

It does work; 
Jenkins does not allow CSS by default, so you have to do the following:
https://stackoverflow.com/questions/35783964/jenkins-html-publisher-plugin-no-css-is-displayed-when-report-is-viewed-in-j 


eg:
CSS is striped because of the Content Security Policy in Jenkins. (https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy)

The default rule is set to:

sandbox; default-src 'none'; img-src 'self'; style-src 'self';
This rule set results in the following:

No JavaScript allowed at all
No plugins (object/embed) allowed
No inline CSS, or CSS from other sites allowed
No images from other sites allowed
No frames allowed
No web fonts allowed
No XHR/AJAX allowed, etc.
To relax this rule, go to Manage Jenkins->Script console and type in the following command :

System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "")
and Press Run. If you see the output as 'Result:' below "Result" header then the protection disabled. Re-Run your build and you can see that the new HTML files archived will have the CSS enabled.

Now you can use the HTML publisher plugin to show it.

hope this helps

**Comment by RamiaSaidawi** [comment]
Thank you @marcowork that was very helpful 
👍

**Comment by T-e-j-k-u-m-a-r** [comment]
Thanks a lot @marcowork : It did work.
