### ISSUE TITLE
mocha.opts --reporter-options issue

### ISSUE THREAD

**Issue by cristian-smocot** [adamgruber/mochawesome#20]
I'm using a ``mocha.opts`` file for ease-of-use config of the CLI arguments that are passed to mocha.

I have discovered that, if for example I have a ``mocha.opts`` file like the following:

``
--reporter mochawesome
--reporter-options reportDir=mocha-reports,reportName=ViewReport,reportTitle=Mocha Tests
``

it will fail because of the space in `reportTitle=Mocha Tests`.

`reportTitle=MochaTests` or `reportTitle=Mocha-Tests` works correctly.

It would be nice to be able to use spaces in the ``report title``, ``reportName``, ``reportDir``parameters of the reporter.

**Comment by adamgruber** [comment]
It's not currently possible to include spaces and this is due to how mocha parses the arguments.

See https://github.com/mochajs/mocha/blob/master/bin/options.js#L25. 

I could include a hack inside Mochawesome but the better solution is to file an issue with mocha or submit a pull request to them. I would think the right way to include spaces in the arguments would be to escape them like this: `--reporter-options reportTitle=title\ with\ spaces` and then the regex that mocha uses for parsing can be updated to respect escaped spaces.

**Comment by adamgruber** [comment]
It's not currently possible to include spaces and this is due to how mocha parses the arguments.

See https://github.com/mochajs/mocha/blob/master/bin/options.js#L25. 

I could include a hack inside Mochawesome but the better solution is to file an issue with mocha or submit a pull request to them. I would think the right way to include spaces in the arguments would be to escape them like this: `--reporter-options reportTitle=title\ with\ spaces` and then the regex that mocha uses for parsing can be updated to respect escaped spaces.

**Comment by adamgruber** [comment]
I submitted a pull request to mocha that would allow you to pass an option with a space in it as long as the space is escaped. https://github.com/mochajs/mocha/pull/1774

**Comment by adamgruber** [comment]
Closing this issue as [mocha 2.3.0](https://github.com/mochajs/mocha/releases/tag/2.3.0) is now out and includes the pull request.
