### ISSUE TITLE
enhancement: auto expand additional context

### ISSUE THREAD

**Issue by opub** [adamgruber/mochawesome#217]
I need to save a copy of the report to a PDF with all of my additional context screenshots, etc. visible. Is there an option to have the context visible by default without manually having to click and expand each?

This is a great product! Keep up the good work. Thanks.

**Comment by adamgruber** [comment]
Thanks for the feedback @opub!

Unfortunately there's currently no easy way to expand all tests. There's also no setting to default them to an expanded state and I'm not sure I'd add something like that. I'm not sure how many tests you have but for each test the report does not render the expanded info into the DOM initially. The render only happens upon clicking. This is important because it significantly cuts down on the number of DOM nodes that need to be rendered. Since rendering in the DOM is typically the slowest operation, this can save many seconds of load time for large test suites.

A possible solution would be to add a button that toggles expansion for all tests. I'll have to think through this a bit to see if it makes sense and where it would live.

**Comment by opub** [comment]
Understood. What if there was a way to add a custom script or HTML to the report template? That could at least provide the hook to have my own expansion code execute when the report is opened. Something similar could also be useful for people looking to adjust the layout or branding of the report.

**Comment by adamgruber** [comment]
The report has been carefully designed and thought out to optimally present the results of a test run. There are no plans to support adjusting the layout or adding custom branding. If this is something you require, you could add some kind of post-processing after the report has been generated.

**Comment by ksvvandana** [comment]
Is this enhancement made?
