### ISSUE TITLE
Want to Pass some data in test Report

### ISSUE THREAD

**Issue by ankansithole** [adamgruber/mochawesome#227]
Hello,

I want to pass some data test report so that i can identify the reason of failure.
Please help how can i pass.
currently i pass or fail test case using assert statement

**Comment by adamgruber** [comment]
Have you looked at using [context](https://github.com/adamgruber/mochawesome/#adding-test-context)?

**Comment by ankansithole** [comment]
Yes, but i want pass to pass some results in reports.
If assert statement fails then how to send some data in results i.e, reason of failure

**Comment by ankansithole** [comment]
One more Question:
If test case is failed then context isn't showing in results.
is there any issue??

**Comment by ankansithole** [comment]
Hey please reply

**Comment by adamgruber** [comment]
Hey. I haven't had a chance to look into this any further. Understand that this is a side project so it's often difficult to find time to review and respond to issues.

As far as I am aware, `addContext` works as expected. If you have evidence otherwise, please provide an example of the code you are working with, the results you are getting, and the output you expect to see. As it stands I don't have much to go on from your comments.

For more info, please review the guidelines on [submitting issues](https://github.com/adamgruber/mochawesome/blob/master/CONTRIBUTING.md#submitting-issues).
