### ISSUE TITLE
Add the ability to determine the screenshot and video file path

### ISSUE THREAD

**Issue by Tackgnol** [adamgruber/mochawesome#311]
**Is your feature request related to a problem? Please describe.**
Right now the files get saved to an arbitrary directory in `/cypress`
This means that any reports need to do a weird pathing to those ;( 

**Describe the solution you'd like**
I would like to be able to add an option --screenshotDir `/where/screenshots/need/to/be`  --videoDir `/where/videos/need/to/be

**Describe alternatives you've considered**
I can write postScripts that move them all but then I have to edit the JSON and it becomes messy...

**Comment by jayseeare** [comment]
This sounds like your having an issue with [cypress](https://github.com/cypress-io/cypress) rather than mochawesome to me, in which case you might have better luck with an issue in their repo. 

That said, if that is the case then you can configure the videos and screenshots directories with the `cypress.config` entries `screenshotsFolder` and `videosFolder`. See the [cypress docs](https://docs.cypress.io/guides/references/configuration.html#Folders-Files)
