### ISSUE TITLE
Table-of-contents sidebar?

### ISSUE THREAD

**Issue by wmhilton** [adamgruber/mochawesome#49]
I just had another enhancement idea: a sticky table-of-contents sidebar that lets you quickly jump to the test suite. Quicker than having to scroll all the time.

**Comment by adamgruber** [comment]
I had played around with this idea but decided against it because I wanted to keep the full width of the page available to the reports. Mostly because the suites already get narrower the more nesting you have and I wanted to accommodate this.

What would you think about a quick nav option in the header? Either a dropdown or a slide over menu?

**Comment by wmhilton** [comment]
Hmm, yes I was using a big ol' monitor so there was plenty of room in the margin. A responsive slide over menu would probably be the best then, so it doesn't eat into the page width. Drop-down menus are tough to use on mobile.






On Thu, May 5, 2016 at 6:13 AM -0700, "Adam Gruber" <notifications@github.com> wrote:












I had played around with this idea but decided against it because I wanted to keep the full width of the page available to the reports. Mostly because the suites already get narrower the more nesting you have and I wanted to accommodate this.



What would you think about a quick nav option in the header? Either a dropdown or a slide over menu?

**Comment by adamgruber** [comment]
Added nav in 1.4.0
