### ISSUE TITLE
Pass/Fail filters

### ISSUE THREAD

**Issue by scott2449** [adamgruber/mochawesome#5]
It looks like the JS code allows for filters to stack or some such nonsense :smiling_imp: 

1) If I click on fail number and that removes all the tests, and then I click on success which shows me 50% of the tests. If keep clicking on success it toggles between 50% and 0% instead of 50% and 100% which is what I would expect. 

2) A visual indication of what filters are in play would also be awesome.

**Comment by adamgruber** [comment]
1. This is the expected behavior. The filters turn on/off the display of those tests. Click 'Passing' it will show you all passing tests. Click 'Failed' and it will show failed tests, in addition to the passing tests that were already showing. Think of the filters as checkboxes and not a radio button group. We could argue which functionality is more 'expected' but it is by no means broken in its current state. It works as intended.

2. There are multiple visual indicators as to what filter(s) are active. In the main summary, an active filter will have bold colored text.The active filters are also underlined in each test summary. I'll concede that these indicators may be too subtle. I can look at enhancing them in a future update.

**Comment by scott2449** [comment]
:rage1: :cow2: :hankey: 

:sleepy:

**Comment by scott2449** [comment]
!! :trophy: !! https://github.com/adamgruber/mochawesome/blob/master/changelog.md#111
