### ISSUE TITLE
[mochawesome] Error: Unable to save mochawesome-reports/mochawesome.html

### ISSUE THREAD

**Issue by ramyaa** [adamgruber/mochawesome#52]
Hi

I am not able to get the json/html reports in the reports folder.
I run the tests using this command:
`mocha test --reporter mochawesome (all my tests are inside the "test" folder)
`
And, I get this error:

> [mochawesome] Error: Unable to save mochawesome-reports/mochawesome.json
> Error: ENOENT: no such file or directory, open 'mochawesome-reports/mochawesome.json'
> [mochawesome] Error: Unable to save mochawesome-reports/mochawesome.html
> Error: ENOENT: no such file or directory, open 'mochawesome-reports/mochawesome.html'
> [mochawesome] Report saved to mochawesome-reports/mochawesome.html

And the **mochawesome-reports** contains:

```
tree mochawesome-reports/
mochawesome-reports/
|-- css
|   |-- mochawesome-64.css
|   `-- mochawesome.css
|-- fonts
|   |-- mochawesome.eot
|   |-- mochawesome.svg
|   |-- mochawesome.ttf
|   |-- mochawesome.woff
|   |-- Roboto+Condensed_300_normal.ttf
|   |-- Roboto+Condensed_300_normal.woff
|   |-- Roboto+Condensed_400_normal.svg
|   |-- Roboto+Condensed_400_normal.ttf
|   |-- Roboto+Condensed_400_normal.woff
|   |-- Roboto+Condensed_700_normal.ttf
|   |-- Roboto+Condensed_700_normal.woff
|   |-- Roboto+Slab_400_normal.svg
|   |-- Roboto+Slab_400_normal.ttf
|   `-- Roboto+Slab_400_normal.woff
`-- js
    |-- mochawesome.js
    `-- vendor.js

3 directories, 18 files

```
How can i get this working?

**Comment by adamgruber** [comment]
Hi. Sorry to hear you are having some issues with the reporter. Looks like the reporter files are getting copied correctly but the actual report is throwing an error when saving. In order to help you better I'll need some more info first. See [CONTRIBUTING.md](https://github.com/adamgruber/mochawesome/blob/master/CONTRIBUTING.md) for how to provide an example. Thanks.

**Comment by codeSasquatch** [comment]
Hey Adam I am experiencing a similar issue for me it is the pending tests inside mocha that is throwing an exception.     

here is my commandline inside the folder "mocha Googl1.js --reporter mochawesome"

I am using:
Mocha 2.4.5
MochAwesome 1.3.4
Selenium-Webdriver 2.53.2
ChromeDriver 2.21 this just needs to be installed in a directory that has a Path Variable, I put it inside node.js folder
[download chromedriver.exe](http://chromedriver.storage.googleapis.com/index.html)

Here is my example test and helper file to simplify setup.
[PendingTest.zip](https://github.com/adamgruber/mochawesome/files/270939/PendingTest.zip)

**Comment by ramyaa** [comment]
Hi 

Here are the required details:
```
 sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21
```

```
Mocha Version: "mocha": "^2.4.5"
Mochawesome Version: "mochawesome": "^1.3.4"
```

calling mocha as : 
`npm test`
and the package.json has:
`"scripts": {
    "test": "mocha test/**.js  --reporter mochawesome"
  },`

Thanks!

**Comment by adamgruber** [comment]
@codeSasquatch Thanks for the test code. I was able to use it to debug. The issue actually lies in how selenium-webdriver is wrapping the test function. They don't seem to properly handle pending tests.

If you replace
```js
c.test.it('View Google and Enter in mochawesome');
```
with
```js
c.test.xit('View Google and Enter in mochawesome', function(done) {
  done();
});
```
everything will work properly and your test will still be labeled as pending.

**Comment by adamgruber** [comment]
@ramyaa Can you also provide a sample of your test code that is failing?

**Comment by codeSasquatch** [comment]
Thanks Adam your a great contributor to the global community :)

**Comment by ramyaa** [comment]
[sample.zip](https://github.com/adamgruber/mochawesome/files/273116/sample.zip)

Attached the sample file which still gives the error.

Thanks
Ramya

**Comment by adamgruber** [comment]
@ramyaa Thanks for the sample. It fails for you because you are changing the working directory during the test. The initial reporter directory and files are created/copied before the tests begin to run so when that happens the working directory is `sample/`. After your tests run, the working directory has changed to `private/var/folders/...` and so the reporter cannot find the `sample/mochawesome-reports` directory and nothing is saved.

If you need to change the working directory inside your tests, make sure you change them back in the `after()` method and it should work.

**Comment by ramyaa** [comment]
Thanks a ton @adamgruber - Working fine now, after making the changes you suggested! 
Resolving this issue.
