### ISSUE TITLE
Is it possible to add - capture screenshot oprion

### ISSUE THREAD

**Issue by DeChrish** [adamgruber/mochawesome#59]
Hi,
If the test passes or fails, is it possible to take screenshot and add it to the test steps?

**Comment by adamgruber** [comment]
Sorry, this isn't something that mochawesome can do. As a reporter, it just takes the test output JSON and formats it into a nice HTML page. Taking screenshots would have to be incorporated as part of your test. Also, even if you have that working there is currently no way to get that screenshot into the report since it isn't part of the test suite object.
