### ISSUE TITLE
Error Sending to VALID addresses

### ISSUE THREAD

**Issue by mroien** [adamgruber/mochawesome#72]
Is anyone having the issue where some jobs in Jenkins are sending emails out and then other jobs with same email list are getting the error "Error sending to the following VALID addresses:"?? The console log for the job at the top is cutting part of it off with "Skipping 1,363 KB.. Full Log". Is the log too long so errors on sending the emails? 

Mocha: 2.5.3
Mochawesome: mochawesome-screenshots@1.0.6
Using npm script to call mocha ... --reporter

Any help would be great, thanks.

**Comment by adamgruber** [comment]
Ok a couple things here. First, sounds like you have an issue with Jenkins that is unrelated to the reporter you are using. That "Full Log" text should be a link to see the full Jenkins log because Jenkins will trim the output of long logs for easier viewing. Second, the reporter you are using is `mochawesome-screenshots` which is an older fork of `mochawesome` and so it wouldn't be supported here. Though like I said I don't think the issue has to do with the reporter.

**Comment by mroien** [comment]
OK, thank you. I just thought this might help. You can close the issue if it does not belong here, and thanks for your time. :D
