### ISSUE TITLE
Running mocha from the browser

### ISSUE THREAD

**Issue by paveldk** [adamgruber/mochawesome#83]
Hi,

First of all - kudos for the great job on the project.
For one of my projects I'm having a setup similar to this one - https://gist.github.com/michaelcox/3800736 where I'm running mocha from the browser with requirejs. Is there any way to make mochawesome run as reporter when running mocha in the browser. 

Thanks in advance

**Comment by adamgruber** [comment]
No, not currently. Mochawesome is designed to run on node so it would require major changes to make it work in the browser.

**Comment by rugk** [comment]
Can you please:
1. re-open this. At least PRs may be accepted for that.
2. re-consider this. IMHO, this is actually the best use case for this project. Why generate an HTML file in node and manually open it in a browser? That makes no sense, when I consider how to test my code/display my test results. (It only makes sense for documentation, but not for live-testing.) As such, running tests directly inside the browser and displaying it as HTML would be the preferred result.

If you cannot do/take that yourself, you could tag it with "help wanted".

Also, your lib [is linked on the mocha site](https://mochajs.org/#running-mocha-in-the-browser), below the headline "Running mocha in your browser". So, actually, that's not possible with this here. :disappointed:

**Comment by DonaldBough** [comment]
So I ran into this issue, and figured out running mocha and/or mochawesome through the browser was a frustrating process. A hacky solution is to simply run mocha as usual from the command line, using `npm test` after creating your package.json except you open the mochawesome.html right after the tests run. So here's what my package.json looks like: `{
  "scripts": {
    "test": "mocha --opts ./mocha.opts && open mochawesome-report/mochawesome.html",
    "open-file": "mochawesome-report/mochawesome.html"
  },
  "devDependencies": {
    "mochawesome": "^3.1.1"
  },
  "dependencies": {}
}
`
mocha.opts:
`--reporter mochawesome`

Just run your mocha test with mochawesome as usual from the command line, and the automatically open the html file.

**Comment by Lindsay-Needs-Sleep** [comment]
Part of the official documentation, under the section "**RUNNING MOCHA IN THE BROWSER**", it says that you can use mochawesome as alternative to HTML reporter.  (https://mochajs.org/#reporting)

But there is no directions on how to do this.  And this issue seems to imply that it is impossible.  

This is confusing/conflicting.  I would really like to be able to to run a custom reporter in the browser.  But maybe the documentation should be updated to let users know that they **can only use the default HTML reporter when in the browser**.  (Just so they don't waste hours like me trying to figure it out.)
