### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by pronebird** [adamgruber/mochawesome#9]
How do you configure it when used with MochaPhantomJS?

This is my gulp file: 

```js
gulp.task('test', function () {
	return gulp.src('tests/runner.html')
    	.pipe( mochaPhantomJS({
    		reporter: 'mochawesome'
    	}) );
});
```

What do I have to drop into runner.html to make it work?

**Comment by adamgruber** [comment]
There seem to be some limitations on third party reporters in mocha-phantomjs. The [documentation](https://github.com/metaskills/mocha-phantomjs#third-party-reporters) states:

>*the reporter does not run in Node.js, but in the browser, and node modules can't be required*

Since mochawesome is a node app and not meant to be run in the browser it looks like it won't work with mocha-phantomjs without modification.

**Comment by pronebird** [comment]
Boom, thanks for explanation.
